In [1]:
import pandas as pd

In [15]:
beaches_data = pd.read_csv('data/Beach_Lab_Data.csv')
beaches_data.tail()

,Culture Test ID,Culture Sample 1 Timestamp,Beach,Culture Sample 1 Reading,Culture Sample 2 Reading,Culture Reading Mean,Culture Note,Culture Sample Interval,Culture Sample 2 Timestamp,DNA Test ID,DNA Sample Timestamp,DNA Sample 1 Reading,DNA Sample 2 Reading,DNA Reading Mean,Latitude,Longitude,Location
17998,87551,06/18/2010 12:00:00 AM,Marion Mahony Griffin,24.3,17.3,20.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0161,-87.6647,"(42.0161, -87.6647)"
17999,95444,08/27/2015 12:00:00 AM,Marion Mahony Griffin,11.0,10.0,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0161,-87.6647,"(42.0161, -87.6647)"
18000,98453,06/19/2007 12:00:00 AM,Marion Mahony Griffin,8.6,14.6,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0161,-87.6647,"(42.0161, -87.6647)"
18001,90194,06/24/2011 12:00:00 AM,Marion Mahony Griffin,3.1,3.1,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0161,-87.6647,"(42.0161, -87.6647)"
18002,91474,06/25/2009 12:00:00 AM,Marion Mahony Griffin,10.9,17.1,13.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0161,-87.6647,"(42.0161, -87.6647)"

In [16]:
beaches = beaches_data[['Beach', 'Latitude', 'Longitude']]
beaches = beaches.loc[~beaches['Beach'].isnull()]
beaches

                       Beach  Latitude  Longitude
376              South Shore   41.7689   -87.5636
377                   Howard   42.0188   -87.6663
378              12th Street   41.8638   -87.6083
379                  Juneway   42.0224   -87.6674
380                  Calumet   41.7142   -87.5299
381                   Foster   41.9785   -87.6515
382                 Montrose   41.9655   -87.6385
383                   Foster   41.9785   -87.6515
384                  Juneway   42.0224   -87.6674
385              63rd Street   41.7827   -87.5748
386              12th Street   41.8638   -87.6083
387                   Foster   41.9785   -87.6515
388                 Osterman   41.9877   -87.6545
389                  Juneway   42.0224   -87.6674
390                   Foster   41.9785   -87.6515
391              Ohio Street   41.8935   -87.6152
392                 Montrose   41.9655   -87.6385
393                   Foster   41.9785   -87.6515
394                    Leone   42.0131   -87.6635
395             North Avenue   41.9148   -87.6273
396                    Leone   42.0131   -87.6635
397                  Juneway   42.0224   -87.6674
398              63rd Street   41.7827   -87.5748
399               Oak Street   41.9032   -87.6235
400                  Rainbow   41.7580   -87.5510
401              South Shore   41.7689   -87.5636
402                 Montrose   41.9655   -87.6385
403                 Montrose   41.9655   -87.6385
404                  Calumet   41.7142   -87.5299
405                  Juneway   42.0224   -87.6674
...                      ...       ...        ...
17973  Marion Mahony Griffin   42.0161   -87.6647
17974  Marion Mahony Griffin   42.0161   -87.6647
17975  Marion Mahony Griffin   42.0161   -87.6647
17976  Marion Mahony Griffin   42.0161   -87.6647
17977  Marion Mahony Griffin   42.0161   -87.6647
17978  Marion Mahony Griffin   42.0161   -87.6647
17979  Marion Mahony Griffin   42.0161   -87.6647
17980  Marion Mahony Griffin   42.0161   -87.6647
17981  Marion Mahony Griffin   42.0161   -87.6647
17982  Marion Mahony Griffin   42.0161   -87.6647
17983  Marion Mahony Griffin   42.0161   -87.6647
17984  Marion Mahony Griffin   42.0161   -87.6647
17985  Marion Mahony Griffin   42.0161   -87.6647
17986  Marion Mahony Griffin   42.0161   -87.6647
17987  Marion Mahony Griffin   42.0161   -87.6647
17988  Marion Mahony Griffin   42.0161   -87.6647
17989  Marion Mahony Griffin   42.0161   -87.6647
17990  Marion Mahony Griffin   42.0161   -87.6647
17991  Marion Mahony Griffin   42.0161   -87.6647
17992  Marion Mahony Griffin   42.0161   -87.6647
17993  Marion Mahony Griffin   42.0161   -87.6647
17994  Marion Mahony Griffin   42.0161   -87.6647
17995  Marion Mahony Griffin   42.0161   -87.6647
17996  Marion Mahony Griffin   42.0161   -87.6647
17997  Marion Mahony Griffin   42.0161   -87.6647
17998  Marion Mahony Griffin   42.0161   -87.6647
17999  Marion Mahony Griffin   42.0161   -87.6647
18000  Marion Mahony Griffin   42.0161   -87.6647
18001  Marion Mahony Griffin   42.0161   -87.6647
18002  Marion Mahony Griffin   42.0161   -87.6647

[17627 rows x 3 columns]

In [17]:
beaches = beaches.drop_duplicates()
beaches

                       Beach  Latitude  Longitude
376              South Shore  41.76890 -87.563600
377                   Howard  42.01880 -87.666300
378              12th Street  41.86380 -87.608300
379                  Juneway  42.02240 -87.667400
380                  Calumet  41.71420 -87.529900
381                   Foster  41.97850 -87.651500
382                 Montrose  41.96550 -87.638500
385              63rd Street  41.78270 -87.574800
388                 Osterman  41.98770 -87.654500
391              Ohio Street  41.89350 -87.615200
394                    Leone  42.01310 -87.663500
395             North Avenue  41.91480 -87.627300
399               Oak Street  41.90320 -87.623500
400                  Rainbow  41.75800 -87.551000
409              57th Street  41.79110 -87.579700
428                   Rogers  42.02130 -87.666600
13355               Hartigan  42.00270 -87.656400
13356                  Fargo  42.01610 -87.664700
13357            North Shore  42.00270 -87.656400
13359                 Loyola  42.01310 -87.663500
13360                   Lane  41.98770 -87.654500
13362           Montrose Dog  41.96869 -87.642617
13365   Margaret T Burroughs  41.83930 -87.607200
13368                Oakwood  41.82110 -87.597600
13376               Columbia  42.00270 -87.656400
13432               Humboldt  41.90643 -87.703717
17275  Marion Mahony Griffin  42.01610 -87.664700

In [18]:
len(beaches)

27

In [19]:
beaches = beaches.reset_index(drop=True)
beaches

                    Beach  Latitude  Longitude
0             South Shore  41.76890 -87.563600
1                  Howard  42.01880 -87.666300
2             12th Street  41.86380 -87.608300
3                 Juneway  42.02240 -87.667400
4                 Calumet  41.71420 -87.529900
5                  Foster  41.97850 -87.651500
6                Montrose  41.96550 -87.638500
7             63rd Street  41.78270 -87.574800
8                Osterman  41.98770 -87.654500
9             Ohio Street  41.89350 -87.615200
10                  Leone  42.01310 -87.663500
11           North Avenue  41.91480 -87.627300
12             Oak Street  41.90320 -87.623500
13                Rainbow  41.75800 -87.551000
14            57th Street  41.79110 -87.579700
15                 Rogers  42.02130 -87.666600
16               Hartigan  42.00270 -87.656400
17                  Fargo  42.01610 -87.664700
18            North Shore  42.00270 -87.656400
19                 Loyola  42.01310 -87.663500
20                   Lane  41.98770 -87.654500
21           Montrose Dog  41.96869 -87.642617
22   Margaret T Burroughs  41.83930 -87.607200
23                Oakwood  41.82110 -87.597600
24               Columbia  42.00270 -87.656400
25               Humboldt  41.90643 -87.703717
26  Marion Mahony Griffin  42.01610 -87.664700

In [20]:
beaches.to_csv('data/beaches.csv', index_label='beach_id')